#!/bin/bash
./bin/compose-html assets/pages-src/ dist/pages/ .html
# mkdir dist # dist itak naredi compose-html
cp -r assets/css dist/css
cp -r assets/fonts dist/fonts
cp -r assets/img dist/img
cp -r assets/js dist/js
find assets/root/ \( ! -name "*.bvr" \) -exec cp "{}" dist/  \;
find assets/root/* -exec ./bin/compose-single "{}" dist/"{}" \;
